### ISSUE TITLE
Code Conventions, Formatters, and Linting

### ISSUE THREAD

**Issue by christiansmith** [anvilresearch/connect#116]
Up to now it hasn't been difficult to maintain a consistent coding style for this project, but as more folks start contributing it's not a bad idea to formalize conventions, [document them](https://github.com/anvilresearch/connect-docs/issues/12), and adopt tooling that helps us maintain them as easily as possible. 

It may be that in the spirit of harmonious collaboration, both amongst ourselves and with the broader Node/JS community, we'll need to change some of the _de facto_ conventions used throughout this code. I'm good with that, however I'd like to avoid contentious debates and [bikeshedding](https://en.wikipedia.org/wiki/Parkinson's_law_of_triviality) as much as possible.

One option we have is to adopt [JavaScript Standard Style](https://github.com/feross/standard). This option has two advantages. First, there are no configurable options, so there's no room for argument over trivial details. Second, that project includes an automatic formatter. After working with Golang, I've come to greatly appreciate the convenience of this kind of tooling.

Another option (going in the opposite direction) is [ESLint](http://eslint.org/). This option appears to have a more traction and offers an enormous amount of flexibility. At first glance I'm not sure if it has built in automated formatting or if there are formatters available. 

Please share opinions and ideas, especially if you have experience with these tools.

**Comment by vsimonian** [comment]
I like the simplicity of JS Standard Style. Right now (and later), we need to be working on building Connect with good code, not arguing over what it should look like. JSSS looks like the simplest solution, and even though the style is quite different from what I'm personally used to, I'll gladly get up to speed for the common good.

**Comment by vsimonian** [comment]
Created PRs https://github.com/anvilresearch/connect/pull/184, https://github.com/anvilresearch/connect-cli/pull/6, https://github.com/anvilresearch/connect-jwt/pull/4, https://github.com/christiansmith/modinha/pull/12, https://github.com/christiansmith/modinha-redis/pull/7
