### ISSUE TITLE
Slack vs. Gitter

### ISSUE THREAD

**Issue by christiansmith** [anvilresearch/connect#122]
As many of us have noticed, Gitter seems to be having some scaling issues of late. Last night the service went down for quite a long period, prompting us to create a [Slack team](https://anvilresearch.slack.com).

Slack is very popular, full featured and stable. However, there's a bit more friction up front for new people wanting to join in. Gitter, on the other hand, is very convenient for newcomers to the project. 

Many folks have expressed opinions favoring one tool or the other. Others have suggested using Gitter for community support and Slack for contributors. Let's weigh the pros and cons of all the possibilities here.

In the mean time, I'll try to be available on both Gitter and Slack. Thanks!

**Comment by maverickhacks** [comment]
I prefer pmail.

**Comment by vsimonian** [comment]
+1 for Slack. I like Gitter, but they simply haven't proven themselves to be reliable. Google's been using Slack with fantastic success for the Polymer project (over 1,500 users in their chatroom), and so have many others, and there's a great deal of support for it. There's virtually no learning curve and with [slackin](https://github.com/rauchg/slackin) it's incredibly easy for users to join without manually managing invites.

**Comment by adi-ads** [comment]
Should update readme with info for both till we finalise. 
@maverickhacks duke & bear concur with you :)

**Comment by henrjk** [comment]
I found the ability to simply hang out in gitter really helpful for a non-collaborator. I think without a similar channel which everybody can easily join it would be far more difficult to connect with the team.

**Comment by Cynfusion** [comment]
That's an important point @henrjk, and it's my main objection to slack. I think the bar needs to be really low right now for people to have access and be able to ask questions.

**Comment by Cynfusion** [comment]
Maybe we can have the best of both worlds, I found this potential solution: https://sameroom.io/blog/connecting-a-channel-in-slack-to-a-room-in-gitter/

**Comment by Cynfusion** [comment]
And we can! I have it working, you can use the client you like best and it will update both the slack general channel and gitter.

**Comment by christiansmith** [comment]
@Cynfusion you are awesome!
