### ISSUE TITLE
sentinel support and ioredis

### ISSUE THREAD

**Issue by christiansmith** [anvilresearch/connect#125]
Even as we're looking to roll our own embedded distributed backend and move away from Redis, users are asking for high-availability Redis support. 

Recently someone reached out by email to ask about porting to [ioredis](https://github.com/luin/ioredis), in order to support [sentinel](http://redis.io/topics/sentinel). Looks like it _could_ be fairly straightforward to switch redis clients. Anyone interested to work on this?

**Comment by vsimonian** [comment]
I think prior to this we should run through connect and rip out any redis-specific code and work it into modinha-redis.

**Comment by christiansmith** [comment]
@vsimonian yes, we'd have to. Although in doing that, we'd make modinha-redis specific to this application. I think that's probably an acceptable tradeoff since it's very unlikely that that particular lib is in use anywhere else.

**Comment by vsimonian** [comment]
`ioredis` is named such because it requires `io.js` instead of `node.js`, correct? If so, how's the integration of `node.js` and `io.js` coming along?

**Comment by vsimonian** [comment]
Re: my last comment, it looks like the name doesn't refer to io.js in particular, and ioredis supports node.js as well. Sounds like a go to me.

**Comment by christiansmith** [comment]
I think this might be a good weekend hack.

**Comment by vsimonian** [comment]
:+1:
