### ISSUE TITLE
Boot time database init to deprecate `nv migrate`

### ISSUE THREAD

**Issue by christiansmith** [anvilresearch/connect#128]
There are a handful of values that _must_ exist in the database in order for the server to work as expected. These include the `openid`, `profile`, and `realm` scopes and the `authority` role, along with default permissions.

At present, these values are created by running `nv migrate` before first running the server. This is not ideal for a variety of reasons. First, if overlooked, auth flows won't work correctly. Second, it's a pain to run this in the context of a Docker based deployment. 

I propose that as part of the bootstrapping process, the server should check the database for the existence of these values and create them if they're missing. This also gives us a convenient place in the code the throw an error if the database is unreachable, resolving #39.

**Comment by christiansmith** [comment]
A draft of this behavior (sans unreachable Redis error) now lives in the `bootdb` branch: https://github.com/anvilresearch/connect/commit/904d7447cc31a6c7184d477b82cd6113b0feb4b4

**Comment by vsimonian** [comment]
Merged #142
