### ISSUE TITLE
Eliminate repetitive code in signin, signup, and signout

### ISSUE THREAD

**Issue by vsimonian** [anvilresearch/connect#143]
There exists a number of passages of code in signin, signup, and signout which are repeated throughout with minor differences.

- **oidc/signout.js** lines [43-45](https://github.com/anvilresearch/connect/blob/a96f0a5801/oidc/signout.js#L43-L45), [57-59](https://github.com/anvilresearch/connect/blob/a96f0a5801/oidc/signout.js#L57-L59), [73-75](https://github.com/anvilresearch/connect/blob/a96f0a5801/oidc/signout.js#L73-L75), [81-83](https://github.com/anvilresearch/connect/blob/a96f0a5801/oidc/signout.js#L81-L83)
- **routes/signin.js** lines [78-85](https://github.com/anvilresearch/connect/blob/a96f0a5801/routes/signin.js#L78-L85) and **routes/signup.js** lines [67-74](https://github.com/anvilresearch/connect/blob/a96f0a5801/routes/signup.js#L67-L74)

**Comment by christiansmith** [comment]
Just to give everyone else context, we took a crack at this and Passport complicates the matter because of the way it monkey patches `http.req`. The code we ended up with on the first pass seemed dirtier than having some repetition so we backed out the changes. Ugh.
