### ISSUE TITLE
Create mechanism for generic expiring tokens

### ISSUE THREAD

**Issue by vsimonian** [anvilresearch/connect#168]
Many times, with use-cases such as e-mail verification, password reset, or other similar features, there is a need to make a generic expiring token that is then issued to the user for a particular purpose.

We need to provide some mechanism to enable this, rather than reimplementing this logic for every possible feature.

**Comment by christiansmith** [comment]
It's worth considering using a JWT for this. There may be good reasons not to do that. If not, what type of value? Hash? Also, we may or may not want to persist these tokens. If persisted, they should have a TTL to keep from exploding the size of the database.

**Comment by vsimonian** [comment]
Related: #169

**Comment by christiansmith** [comment]
Really like the way this is turning out. Thanks for pairing today. Awesome work!
