### ISSUE TITLE
Configurable refresh of user claims upon call to userinfo

### ISSUE THREAD

**Issue by uberfirestone** [anvilresearch/connect#181]
Some clients may require pulling an update from the definitive source of a user's claims before the userinfo object is returned. 

This might be configurable at the provider level. (discussed 08/19/2015 in Gitter)

**Comment by christiansmith** [comment]
Added `refresh_userinfo` option with release 0.1.48. You can configure this property for the entire server or for a specific provider.

This is a step forward, doesn't quite solve the problem if I understand the requirements. I believe implementing #10 will bring us closer to getting it right. We've escalated that to a P1 and I'm closing this issue.
