### ISSUE TITLE
Strip leading/trailing whitespace from JSON inputs.

### ISSUE THREAD

**Issue by LegallyGeek** [anvilresearch/connect#220]
When I created a client account, I fat fingered and did 

`"redirect_uris": [" https://`  

Notice the space in front of the https?  When you do calls later, if the passed referring URL doesn’t include the leading space it throws a redirect mismatch.  If possible, stripping leading and trailing whitespace for JSON values may help avoid this.

**Comment by christiansmith** [comment]
Thanks @LegallyGeek. Great catch.
