### ISSUE TITLE
Node version check

### ISSUE THREAD

**Issue by msamblanet** [anvilresearch/connect#235]
However, since that only produces a warning, application startup should also check and verify the version of node or refuse to start

package.json does have an engines line in there but it only produces a warning which is easily missed

I may be able to contribute a patch for this if I have time before others get to it.

**Comment by vsimonian** [comment]
:+1: Good catch! If you'd like to submit a patch (and thus, gain credit for authorship), feel free. Otherwise, we can throw something together if you're preoccupied.

**Comment by msamblanet** [comment]
Likely easy solution: [nodeversioncheck](https://www.npmjs.com/package/nodeversioncheck)

**Comment by vsimonian** [comment]
Woah, nice find. @christiansmith, what do you think?

**Comment by christiansmith** [comment]
Who wants to submit the PR? I think this should probably go in `server.js` or `boot/server.js`.

**Comment by msamblanet** [comment]
Looking closer, nodeversioncheck relies on CWD being where the top level package.json is - is this reliable for all the ways connect and connect-cli are launched?  If not, then likely should just do it manually (which is not all that hard)

**Comment by vsimonian** [comment]
Good point. Then, in `server.js` or `boot/server.js` we can throw a simple `if` that checks `package.json`'s `engine` property with `semver`. `require('./package.json')` in the context of the anvil-connect package should always pull the right file.

**Comment by msamblanet** [comment]
That was how I did it in my last project - the simple require() approach would have had a nice cleanliness, but what you going to do...if there are 5 solutions on the internet, none of them meet your assumptions and you create number 6....

**Comment by msamblanet** [comment]
Untested proposed check code:

```js
// In package.json, add dependency:    "semver": "^5.0.3"

var semver = require('semver')
var packageJson = require('../package.json')
if (packageJson.engines && 
    packageJson.engines.node && 
    !semver.satisfies(process.versions.node, packageJson.engines.node)) {
	console.error('Incompatible version of node - found %s but require %s',
            process.versions.node, packageJson.engines.node)
	process.exit(1)
}
```

**Comment by christiansmith** [comment]
Thanks @msamblanet
