### ISSUE TITLE
Selecting a template language

### ISSUE THREAD

**Issue by christiansmith** [anvilresearch/connect#24]
We used Jade for view rendering out of the gate, since it's the default template language for Express and it was easy to get started. However, Jade is, by all accounts, the [worst performer](https://github.com/baryshev/template-benchmark) among JavaScript templating engines and the syntax is controversial and foreign to many developers.

Since performance is a major objective and we're exposing templates to be overridden and customized for a given deployment, it makes sense to evaluate alternatives. I'm leaning strongly toward choosing [Hogan.js](http://twitter.github.io/hogan.js/) for its speed (third in the benchmarks among 15 contenders) and simple, familiar syntax.

Does anyone want to weigh in before we go down this path?

**Comment by christiansmith** [comment]
Anyone want to help incorporate `consolidate.js` into Connect? The idea would be to let users choose the templating language of their choice.

https://github.com/tj/consolidate.js

**Comment by bnb** [comment]
That sounds like a _very_ good idea for helping adoption gain traction and retain momentum. I would mark integrating consolidate as a top priority.

**Comment by christiansmith** [comment]
https://github.com/anvilresearch/connect/commit/e955ad2c5f6a24001d821015e9eb884f85f8bc44 incorporates consolidate.js.

The view engine still defaults to jade and can be configured with the `view_engine` setting in your config file. I'm not sure if this will work as expected with other engines besides jade, but we're a step closer.

**Comment by vsimonian** [comment]
Through the past month, consensus has generally maintained that we will be switching to Hogan. The new e-mail verification #123 functionality is using Hogan by default.

Should we close this issue and open a new one titled "Use Hogan.js as default template engine"?
