### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by AlexZeitler** [anvilresearch/connect#261]
First things first: thanks for your great work so far!

I've a simple question: Would you consider `connect` to be ready for production use?
If not: what are the blockers?

**Comment by christiansmith** [comment]
@AlexZeitler thanks for your kind words.

This code has been run in production by several enterprise and web users for more than one year with no reported operational issues.

We do not yet have a "stable" release, meaning parts of the code are still in flux and there ~~may~~ _will_ be a few breaking changes as we continue to make improvements to the design and usability of the software. 

We're hoping to release an `0.2.0` branch by the end of this year. That branch will only receive bug fixes and security patches, while further breaking changes will take place in master or `0.3.0`. 

The biggest blockers for adoption at the moment I believe are related to usability. We need better documentation and we're hard at work improving the developer experience. If you're willing to get your hands dirty and participate in the discussions on Gitter, Slack or IRC, Anvil Connect is ready to go.

**Comment by AlexZeitler** [comment]
@christiansmith Thanks for your fast reply.

I'll try to get things ready and will hop in to Slack if I need some guidance.
If possible I'll try to contribute to the docs at least.
