### ISSUE TITLE
Issuer Config - response_types_supported includes none

### ISSUE THREAD

**Issue by msamblanet** [anvilresearch/connect#263]
The issuer config returned by discovery is including a value of "none" - this is not listed in the spec.  Is this an error or something internal?  Auth with no response type seems a non-sequitor to me.

```
{
  "issuer": "https://anvil.connect.example.com",
  "authorization_endpoint": "https://anvil.connect.example.com/authorize",
  "token_endpoint": "https://anvil.connect.example.com/token",
  "userinfo_endpoint": "https://anvil.connect.example.com/userinfo",
  "jwks_uri": "https://anvil.connect.example.com/jwks",
  "registration_endpoint": "https://anvil.connect.example.com/register",
  "scopes_supported": [
    "realm",
    "client",
    "profile",
    "openid"
  ],
  "response_types_supported": [
    "code",
    "code token",
    "code id_token",
    "id_token",
    "id_token token",
    "code id_token token",
    "none"
  ],
  "response_modes_supported": [],
  "grant_types_supported": [
    "authorization_code",
    "refresh_token"
  ],
  "acr_values_supported": [],
  "subject_types_supported": [
    "public"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "id_token_encryption_alg_values_supported": [],
  "id_token_encryption_enc_values_supported": [],
  "userinfo_signing_alg_values_supported": [
    "none"
  ],
  "userinfo_encryption_alg_values_supported": [],
  "userinfo_encryption_enc_values_supported": [],
  "request_object_signing_alg_values_supported": [],
  "request_object_encryption_alg_values_supported": [],
  "request_object_encryption_enc_values_supported": [],
  "token_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post"
  ],
  "token_endpoint_auth_signing_alg_values_supported": [],
  "display_values_supported": [],
  "claim_types_supported": [
    "normal"
  ],
  "claims_supported": [
    "iss",
    "sub",
    "aud",
    "acr",
    "name",
    "given_name",
    "family_name",
    "middle_name",
    "nickname",
    "preferred_username",
    "profile",
    "picture",
    "website",
    "email",
    "email_verified",
    "zoneinfo",
    "locale",
    "joined_at",
    "updated_at"
  ],
  "service_documentation": "http://anvil.io/docs/connect/",
  "claims_locales_supported": [],
  "ui_locales_supported": [],
  "check_session_iframe": "https://anvil.connect.example.com/session",
  "end_session_endpoint": "https://anvil.connect.example.com/signout"
}
```

**Comment by vsimonian** [comment]
The `none` response type is [defined in OAuth2](http://openid.net/specs/oauth-v2-multiple-response-types-1_0-08.html#none) as such:

>This section registers the response type none, in accordance with the stipulations in the OAuth 2.0 specification, Section 8.4. The intended purpose is to enable use cases where a party requests the server to register a grant of access to a Protected Resource on behalf of a Client but requires no access credentials to be returned to the Client at that time. The means by which the Client eventually obtains the access credentials is left unspecified here.
>
>One scenario is where a user wishes to purchase an application from a market, and desires to authorize application installation and grant the application access to Protected Resources in a single step. However, since the user is not presently interacting with the (not yet active) application, it is not appropriate to return access credentials simultaneously in the authorization step.
>
>    `none`
>
>    When supplied as the response_type parameter in an OAuth 2.0 authorization request, the Authorization Server SHOULD NOT return an OAuth 2.0 code nor a token in a successful response to the grant request. If a redirect_uri is supplied, the User-Agent SHOULD be redirected there after granting or denying access. The request MAY include a state parameter, and if so the server MUST echo its value by adding it to the redirect_uri when issuing a successful response. Any parameters added to the redirect_uri SHOULD be query encoded. This applies to both successful responses and error responses.
>
>The response type none SHOULD NOT be combined with other response types.

**Comment by msamblanet** [comment]
Duh - I didn't go back to the OAuth spec - I was just looking at the oidc spec.  Sorry about that.

**Comment by christiansmith** [comment]
@msamblanet this is still a good question. I'm really glad to have people reviewing and scrutinizing our code. You folks at @uberether have been tremendously helpful in finding issues and helping us understand some of the dark corners of OIDC.

We have a huge amount of design improvements and refactoring planned and we're looking forward to your ongoing review and collaboration. Thanks for keeping us on our toes.
