### ISSUE TITLE
Coverage data for the Travis build?

### ISSUE THREAD

**Issue by henrjk** [anvilresearch/connect#274]
In a former project we had coverage data for the builds and one could drill down into that just like into the html pages generated locally by issue #272. 

Stackoverflow posting [visual-code-coverage-in-travis-ci](http://stackoverflow.com/questions/15027836/visual-code-coverage-in-travis-ci/20372093#20372093) suggests that travis builds do not keep any data, so that the coverage data would have to be send elsewhere. The Stackoverflow posting mentions coveralls. [travis help lists codeclimate.com](http://docs.travis-ci.com/user/code-climate/#sts=Measuring Test Coverage with Code Climate), which is free for open source projects. 

CodeClimate also does some analysis on the source code, which might be worthwhile as well.

I also found a recent blog post [Better Javascript with Gulp, Mocha, Istanbul and Codeclimate](http://blog.oskoui-oskoui.com/?p=8478)..

Here is an example [dashboard page for node](https://codeclimate.com/github/joyent/node). Unfortunately I did not find any page which actually shows real coverage data and whether one can drill down as nicely as on ones own machine. 

Should there be coverage for our travis builds?

**Comment by christiansmith** [comment]
I think this kind of integration would be very useful, especially when it comes to evaluating PRs. We should make some time to tinker with it, perhaps in another pairing session?

**Comment by henrjk** [comment]
Yes, seems like a good idea to approach this together.

**Comment by henrjk** [comment]
This has been done via coveralls see pull request #293
