### ISSUE TITLE
Stored consent given by users to non-trusted client applications

### ISSUE THREAD

**Issue by EternalDeiwos** [anvilresearch/connect#281]
As far as I know this isn't mentioned anywhere in the spec but it seems to be a common feature in current implementations of OIDC such as Google, GitHub and Facebook.

**Comment by EternalDeiwos** [comment]
Current behavior is to ask for after each login.

**Comment by christiansmith** [comment]
This looks like a duplicate of #26. We can probably sort it out in one or two pairing sessions.

**Comment by christiansmith** [comment]
Great work on #299 @EternalDeiwos. Thanks!
