### ISSUE TITLE
connect-redis - ERR wrong number of arguments for 'set' command

### ISSUE THREAD

**Issue by ikb42** [anvilresearch/connect#298]
`connect-redis version 3.0.1` appears to break anvil-connect when moving from successful user signin to authorize

```
{ [ReplyError: ERR wrong number of arguments for 'set' command] name: 'ReplyError', message: 'ERR wrong number of arguments for \'set\' command', command: { name: 'set', args: [ 'sess:xxxxxxxxxxxxx', '{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"},"amr":["pwd"],"user":"yyyyyyyyyyyyy","opbs":"zzzzzzzzzzz"}', 'EX', '86400' ] } } 

'ReplyError: ERR wrong number of arguments for \'set\' command\n at ReplyParser._parseResult 

(\\connect\\node_modules\\anvil-connect\\node_modules\\ioredis\\lib\\parsers\\ja vascript.js:39:14)\n at ReplyParser.execute (\\connect\\node_modules\\anvil-connect\\node_modules\\ioredis\\lib\\parsers\\javascript.js:139:20)\n at Socket.<anonymous> (\\project\\connect\\node_modules\\anvil-connect\\node_modules\\ioredis\\lib\\redis\\event_handler.js:90:22)\n at emitOne (events.js:77:13)\n at Socket.emit (events.js:169:7)\n at readableAddChunk (_stream_readable.js:146: 16)\n at Socket.Readable.push (_stream_readable.js:110:10)\n at TCP.onread (net.js:523:20)'
```

**Comment by christiansmith** [comment]
@ikb42 thanks so much for helping find the problem and filing the issue. 

Unfortunately, this isn't the first time a dependency has disregarded semantic versioning rules and sent us off on a bug hunt. Perhaps we should consider [shrinkwrapping](https://docs.npmjs.com/cli/shrinkwrap) releases from now on.

**Comment by luin** [comment]
Is it related with https://github.com/tj/connect-redis/issues/164?

**Comment by christiansmith** [comment]
@ikb42 which version of Redis are you running this against?

**Comment by christiansmith** [comment]
@luin thanks for pointing out this possibility :)

**Comment by ikb42** [comment]
redis_version:2.4.6

**Comment by EternalDeiwos** [comment]
@ikb42 would you be able to upgrade your server and see if that fixes the problem? @luin mentioned that redis servers older than 2.6.12 don't allow certain options on the ```SET``` command which seems to be the problem.

**Comment by ikb42** [comment]
Yes, done and all ok on: `redis_version:2.8.2104` and 
```
  "name": "connect-redis",
  "description": "Redis session store for Connect",
  "version": "3.0.1",
```

**Comment by EternalDeiwos** [comment]
Fantastic

**Comment by hardiked** [comment]
This get me out of the problem.
