### ISSUE TITLE
Are you still supporting older (out-of-date) versions of Node.js & IO.js ?

### ISSUE THREAD

**Issue by nelsonic** [anvilresearch/connect#302]
see: https://github.com/anvilresearch/connect/blob/3fa90640ca8af35c94f62d55481d97f03d9264a2/.travis.yml#L5-L8
or can I update these to `4.2.3` (*latest [security release](https://nodejs.org/en/blog/vulnerability/december-2015-security-releases/) from last week)

**Comment by christiansmith** [comment]
It should be safe by now to stop supporting versions prior to 4.x. 

We'll need to update the engines version as well:
- in the [server repo](https://github.com/anvilresearch/connect/blob/3fa90640ca8af35c94f62d55481d97f03d9264a2/package.json#L76)
- and the [cli](https://github.com/anvilresearch/connect-cli/blob/master/templates/connect/package.json#L11)

**Comment by christiansmith** [comment]
@nelsonic come to the weekly hangout and introduce yourself one of these Thursdays at 9am Pacific time.
