### ISSUE TITLE
cli help

### ISSUE THREAD

**Issue by christiansmith** [anvilresearch/connect#34]
The cli tool has subcommands, similar to git or npm, and should support command-specific help.

    $ nv assign --help

**Comment by christiansmith** [comment]
This should be moved to the new independent CLI project:
https://github.com/anvilresearch/connect-cli

**Comment by vsimonian** [comment]
Moved into [anvilresearch/connect-cli#1](https://github.com/anvilresearch/connect-cli/issues/1)
