### ISSUE TITLE
How is this different from coreos/dex?

### ISSUE THREAD

**Issue by pierreozoux** [anvilresearch/connect#343]
Hi,

just discovered your project. I'm trying to understand the SSO scene, and it is not easy as a new comer.
It would be really helpful if you tell me how is it different? It looks like both projects serve the same purpose, but I'm not really sure.

Thanks for your help!

**Comment by christiansmith** [comment]
Hi Pierre,

I can sympathize with the difficulty of understanding this subject. Most everyone explaining how things work tends to do so in terms that are only accessible to those who already understand.

There are a number of other commercial and open source products/projects in this space. We're all implementing the same open standards. I don't have a quick answer to exactly how Anvil is _currently_ differentiated from Dex other than Nodejs vs Golang implementation language. Anvil's initial release predates that of dex by a year. I feel it's healthy to have diversity in the ecosystem.

Our aim has always been to make a suite of accessible, easy to use, lightweight, extensible, and interoperable identity and access management tools that support a variety of related protocols. We try to be pedantic to the specs we implement. To date, the focus has been on OpenID Connect, however, we're paying close attention to new standards in the making and also looking at how we might contribute to that process.

So far getting everything to work flawlessly to spec – _that is a goal, not a claim :)_ – has taken priority over ease of use. The current phase of work will help push us towards the latter goal. We've learned a lot in the past few years from contributors and production users and hopefully that will show in our next major releases.

My advice to newcomers, for the time being, is take a read through the standards specs at a cursory level and get an idea of how they work. No matter which implementation you choose, that will go a long way to helping you use any these tools effectively. 

We have a [references](https://github.com/anvilresearch/connect/wiki/References) doc in the wiki that covers a lot of ground, and you're welcome to join the conversation on [Gitter](https://gitter.im/anvilresearch/connect) or [Slack](https://anvilresearch.slack.com/?redir=%2Faccount%2Fgateways) if you have questions or just want to talk shop.

We also offer workshops on site or remotely if you have a team that needs to get up to speed in a hurry. 

Good luck!

**Comment by pierreozoux** [comment]
Thanks a lot for your feedback!
I'll read what you mentioned.

Have a nice day!
