### ISSUE TITLE
How to Add our magento applications login to anvil connect

### ISSUE THREAD

**Issue by avinashsamala** [anvilresearch/connect#361]
Hi Team,
              I just installed anvil connect in my ubuntu system and i am getting the screen like https://prnt.sc/g68hc1. Now i need to add my applications to anvil connect, please send the process for how to add applications to anvil connect.

Thanks.

**Comment by EternalDeiwos** [comment]
Hi @avinashsamala,

You'll want to start off by reading our [Getting Started](https://github.com/anvilresearch/connect-docs/blob/master/getting-started.md) documentation. Specifically you'll want to take note of our [CLI](https://github.com/anvilresearch/connect-docs/blob/master/cli.md) documentation as well as this is the primary method of interacting with the connect service.

If you are still having further trouble then please @mention me on our gitter channel.

**Comment by avinashsamala** [comment]
Hi EternalDeiwos,
                             I followed same steps but still it showing like https://prnt.sc/g68hc1 only. can u help me on this issue.
Thanks.

**Comment by EternalDeiwos** [comment]
Hi @avinashsamala,

Connect does not have a web-based management interface, management tasks (such as adding clients) are done through our [CLI](https://github.com/anvilresearch/connect-docs/blob/master/cli.md).
