### ISSUE TITLE
Throw error for unreachable Redis instance

### ISSUE THREAD

**Issue by christiansmith** [anvilresearch/connect#39]
Requests hang up when Redis isn't available. We need to fail with a meaningful error right away.

**Comment by vsimonian** [comment]
I'm having a few hiccups on my machine at the moment that I'm still sorting through, so I forget if this issue has been addressed or not.

**Comment by christiansmith** [comment]
Not yet. I think it will be good to work on this in conjunction with #128.

**Comment by christiansmith** [comment]
https://github.com/anvilresearch/connect/commit/faa5942be5776f927be222a9e9babdc393220a7a resolves this.
