### ISSUE TITLE
Split CLI to separate repo and communicate w/server via REST API

### ISSUE THREAD

**Issue by christiansmith** [anvilresearch/connect#44]

**Comment by christiansmith** [comment]
In progress.
https://github.com/christiansmith/anvil-connect-cli

**Comment by vsimonian** [comment]
**Status update**

- `migrate` has been deprecated (#142)
- `init` has been implemented and significantly refactored (https://github.com/anvilresearch/connect-cli/pull/7)

**Comment by christiansmith** [comment]
`nvl` is ready to replace `nv`. We've removed the old CLI code from this repo. I think we can safely close this issue.
