### ISSUE TITLE
Anvil incompatible with Node 0.12.x

### ISSUE THREAD

**Issue by JiCiT** [anvilresearch/connect#91]
I think it's mostly, if not entirely, a bcrypt issue.  I'll try to get more details if I can find the time.

**Comment by christiansmith** [comment]
Should work with Node 0.12.x as of https://github.com/anvilresearch/connect/commit/b7c0a54af88d78bf3c2e9a9b7555fb6f4c29a2b6

Upgraded all the dependencies and I'm running it against 0.12.2 now.

The next release will include this update.

**Comment by JiCiT** [comment]
Cool.  Thanks.
