### ISSUE TITLE
anvil.io 'docs' link in footer points to anvil.io, docs aren't on the site

### ISSUE THREAD

**Issue by bkcsfi** [anvilresearch/connect#94]
only way to read docs is to download the repo or view the .md files in github..

**Comment by christiansmith** [comment]
Sorry for the confusion. I'm working on a major overhaul of the docs right now. They will be viewable on anvil.io and I just started moving the work to [this repository](https://github.com/anvilresearch/connect-docs). 

Not much there at the moment but it's coming very soon. I won't be working on anything else until the docs are solid. 

In the mean time, if you have questions, please come chat on [gitter](https://gitter.im/anvilresearch/connect).

**Comment by bkcsfi** [comment]
thanks, I'll wait.. good podcast on The Web Platform, btw.
